# Generated by Django 4.0.6 on 2022-07-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='hit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
